language: node_js
node_js:
- '6'
- '5'
- '4'
sudo: false

before_script:
  # Generate a virtual framebuffer X server to collect Electron windows
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Wait for Xvfb to start
  - sleep 3
